### ISSUE TITLE
quantile segfaults when quantile out of [0;1] range

### ISSUE THREAD

**Issue by tvondra** [tvondra/quantile#5]
Originally reported on pgsql-bugs by Stephane Wustner - reposting here.

Bug reference:      8587
Logged by:          strexxx
PostgreSQL version: 9.3.0
Operating system:   ubuntu 13.04
Description:

I know this is not the place to submit for the quantile extension, but the
git hub new issue button is broken.

2013-11-11 18:05:53 CET LOG:  server process (PID 28207) was terminated by
signal 11: Segmentation fault
2013-11-11 18:05:53 CET DETAIL:  Failed process was running: select
quantile(generate_series,50) from generate_series(0,997);

I know quantile expect double precision within [0;1], but, maybe you would
like to know it segfaults.

**Comment by achempion** [comment]
May be it's time to close it, because was fixed by https://github.com/tvondra/quantile/commit/c1e7bba9f7f092a8b42d834c21f86bb60a001b15 commit.

**Comment by tvondra** [comment]
Yeah, this was fixed in 1.1.4.
