### ISSUE TITLE
installable via create extension?

### ISSUE THREAD

**Issue by contra** [tvondra/quantile#8]
Any plans to make this possible or is it currently possible?

```
CREATE EXTENSION IF NOT EXISTS quantile;
```

**Comment by tvondra** [comment]
I don't follow - what exactly is the problem? AFAIK it's not possible to install custom C extensions on RDS, because it's a restricted environment, but that's not something I can fix.

**Comment by contra** [comment]
@tvondra They'll approve extensions if asked enough - they have quite a few actually (PostGIS being a major one).

My question is: What do we need to do to make this work with the `CREATE EXTENSION` command? If I understand correctly, PGXN is a different system and doesn't work this way. My goal is to have a setup as similar as possible to PostGIS.

I'm not super familiar with how the Postgres extension system works (or PGXN) so let me know if I'm wrong here.

**Comment by contra** [comment]
@tvondra Would you be interested in a brew formula for installing this?
